#!/usr/bin/env python3
"""Generate E8 ML2 readiness reports (HTML).

Usage:
    python3 generate_report.py --type weekly \
        --patch-data patch-compliance.json \
        --vuln-data prioritised.json \
        --output weekly-report.html

    python3 generate_report.py --type executive \
        --patch-data patch-compliance.json \
        --vuln-data prioritised.json \
        --output exec-summary.html

    python3 generate_report.py --type evidence-pack \
        --patch-data patch-compliance.json \
        --vuln-data prioritised.json \
        --output evidence/
"""

import os
import sys
import json
import argparse
from datetime import datetime, timezone
from pathlib import Path

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  :root {{
    --bg: #0f172a; --surface: #1e293b; --border: #334155;
    --text: #e2e8f0; --muted: #94a3b8;
    --green: #22c55e; --yellow: #eab308; --orange: #f97316; --red: #ef4444;
    --blue: #3b82f6;
  }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
         background: var(--bg); color: var(--text); padding: 2rem; line-height: 1.6; }}
  .container {{ max-width: 900px; margin: 0 auto; }}
  h1 {{ font-size: 1.8rem; margin-bottom: 0.5rem; }}
  h2 {{ font-size: 1.3rem; margin: 2rem 0 1rem; border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; }}
  .subtitle {{ color: var(--muted); margin-bottom: 2rem; }}
  .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; margin: 1rem 0; }}
  .card {{ background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 1.2rem; }}
  .card .label {{ color: var(--muted); font-size: 0.85rem; text-transform: uppercase; letter-spacing: 0.05em; }}
  .card .value {{ font-size: 2rem; font-weight: 700; margin-top: 0.3rem; }}
  .card .value.green {{ color: var(--green); }}
  .card .value.yellow {{ color: var(--yellow); }}
  .card .value.orange {{ color: var(--orange); }}
  .card .value.red {{ color: var(--red); }}
  table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
  th, td {{ text-align: left; padding: 0.6rem 0.8rem; border-bottom: 1px solid var(--border); }}
  th {{ color: var(--muted); font-size: 0.85rem; text-transform: uppercase; }}
  .badge {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.8rem; font-weight: 600; }}
  .badge.critical {{ background: var(--red); color: white; }}
  .badge.high {{ background: var(--orange); color: white; }}
  .badge.medium {{ background: var(--yellow); color: #1e293b; }}
  .badge.low {{ background: var(--blue); color: white; }}
  .footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border);
             color: var(--muted); font-size: 0.85rem; }}
  .status-ok {{ color: var(--green); }} .status-warn {{ color: var(--yellow); }} .status-fail {{ color: var(--red); }}
</style>
</head>
<body>
<div class="container">
{content}
<div class="footer">
  <p>Generated by E8CR VM+PM Bot — {generated_at}</p>
  <p>Essential Eight Control Room — Dobson Development</p>
</div>
</div>
</body>
</html>"""


def load_json(path):
    if not path or not os.path.exists(path):
        return None
    with open(path) as f:
        return json.load(f)


def compliance_color(pct):
    if pct >= 95:
        return "green"
    elif pct >= 80:
        return "yellow"
    elif pct >= 60:
        return "orange"
    return "red"


def generate_weekly(patch_data, vuln_data):
    """Generate weekly readiness report HTML."""
    now = datetime.now(timezone.utc)
    content = f"<h1>🛡️ Essential Eight — Weekly Readiness Report</h1>\n"
    content += f'<p class="subtitle">Week ending {now.strftime("%d %B %Y")}</p>\n'

    # Patch compliance section
    if patch_data:
        rate = patch_data.get("compliance_rate", 0)
        total = patch_data.get("total_devices", 0)
        compliant = patch_data.get("patch_compliance", {}).get("compliant", 0)
        noncompliant = patch_data.get("patch_compliance", {}).get("noncompliant", 0)
        stale = patch_data.get("stale_count", 0)
        eol = patch_data.get("eol_count", 0)

        content += "<h2>Patch Compliance</h2>\n"
        content += '<div class="grid">\n'
        content += f'<div class="card"><div class="label">Compliance Rate</div><div class="value {compliance_color(rate)}">{rate}%</div></div>\n'
        content += f'<div class="card"><div class="label">Total Devices</div><div class="value">{total}</div></div>\n'
        content += f'<div class="card"><div class="label">Compliant</div><div class="value green">{compliant}</div></div>\n'
        content += f'<div class="card"><div class="label">Non-Compliant</div><div class="value {"red" if noncompliant > 0 else "green"}">{noncompliant}</div></div>\n'
        content += f'<div class="card"><div class="label">Stale (14d+)</div><div class="value {"orange" if stale > 0 else "green"}">{stale}</div></div>\n'
        content += f'<div class="card"><div class="label">End-of-Life OS</div><div class="value {"red" if eol > 0 else "green"}">{eol}</div></div>\n'
        content += '</div>\n'

        # EOL devices table
        if patch_data.get("eol_devices"):
            content += '<h2>⚠️ End-of-Life Devices (Non-Compliant)</h2>\n'
            content += '<table><tr><th>Device</th><th>OS Version</th><th>User</th><th>Action Required</th></tr>\n'
            for d in patch_data["eol_devices"]:
                content += f'<tr><td>{d["deviceName"]}</td><td>{d["osVersion"]}</td><td>{d.get("user", "-")}</td><td class="status-fail">Upgrade or decommission</td></tr>\n'
            content += '</table>\n'

        # Stale devices table
        if patch_data.get("stale_devices"):
            content += '<h2>⚠️ Stale Devices (Not Synced 14+ Days)</h2>\n'
            content += '<table><tr><th>Device</th><th>Days Since Sync</th><th>User</th></tr>\n'
            for d in patch_data["stale_devices"][:15]:
                content += f'<tr><td>{d["deviceName"]}</td><td>{d["daysSinceSync"]}</td><td>{d.get("user", "-")}</td></tr>\n'
            content += '</table>\n'

    # Vulnerability section
    if vuln_data:
        total_vulns = vuln_data.get("total_findings", 0)
        kev = vuln_data.get("kev_matches", 0)
        breakdown = vuln_data.get("priority_breakdown", {})

        content += "<h2>Vulnerability Management</h2>\n"
        content += '<div class="grid">\n'
        content += f'<div class="card"><div class="label">Total Findings</div><div class="value">{total_vulns}</div></div>\n'
        content += f'<div class="card"><div class="label">CISA KEV Matches</div><div class="value {"red" if kev > 0 else "green"}">{kev}</div></div>\n'
        content += f'<div class="card"><div class="label">P1 Critical</div><div class="value {"red" if breakdown.get("P1-CRITICAL", 0) > 0 else "green"}">{breakdown.get("P1-CRITICAL", 0)}</div></div>\n'
        content += f'<div class="card"><div class="label">P2 High</div><div class="value {"orange" if breakdown.get("P2-HIGH", 0) > 0 else "green"}">{breakdown.get("P2-HIGH", 0)}</div></div>\n'
        content += '</div>\n'

        # Top vulnerabilities table
        results = vuln_data.get("results", [])
        if results:
            content += '<h2>Top Priority Vulnerabilities</h2>\n'
            content += '<table><tr><th>Priority</th><th>Score</th><th>Host</th><th>CVEs</th><th>Name</th><th>ML2 SLA</th></tr>\n'
            for r in results[:20]:
                badge_class = r["priority"].split("-")[1].lower()
                cves = ", ".join(r.get("cves", [])[:2]) or "-"
                name = r.get("name", "")[:60]
                sla = r.get("ml2_sla", "-")
                kev_flag = " 🔴" if r.get("in_cisa_kev") else ""
                content += f'<tr><td><span class="badge {badge_class}">{r["priority"]}</span>{kev_flag}</td>'
                content += f'<td>{r["priority_score"]}</td><td>{r["host"]}</td><td>{cves}</td><td>{name}</td><td>{sla}</td></tr>\n'
            content += '</table>\n'
            if len(results) > 20:
                content += f'<p class="muted">... and {len(results) - 20} more findings</p>\n'

    # ML2 readiness summary
    content += "<h2>ML2 Readiness — Patch Controls</h2>\n"
    content += '<table><tr><th>Control</th><th>Status</th><th>Notes</th></tr>\n'

    if patch_data:
        rate = patch_data.get("compliance_rate", 0)
        eol = patch_data.get("eol_count", 0)
        stale = patch_data.get("stale_count", 0)

        patch_status = "status-ok" if rate >= 95 and eol == 0 else ("status-warn" if rate >= 80 else "status-fail")
        content += f'<tr><td>Patch Applications</td><td class="{patch_status}">{"✅ On Track" if rate >= 95 and eol == 0 else "⚠️ Gaps Found" if rate >= 80 else "❌ Non-Compliant"}</td>'
        content += f'<td>{rate}% compliant, {eol} EOL devices, {stale} stale</td></tr>\n'

        content += f'<tr><td>Patch Operating Systems</td><td class="{patch_status}">{"✅ On Track" if rate >= 95 and eol == 0 else "⚠️ Gaps Found" if rate >= 80 else "❌ Non-Compliant"}</td>'
        content += f'<td>See above — OS and app patching tracked together</td></tr>\n'

    if vuln_data:
        scan_status = "status-ok"  # We have scan data, so scanning is happening
        content += f'<tr><td>Vulnerability Scanner (fortnightly)</td><td class="{scan_status}">✅ Active</td>'
        content += f'<td>Last scan data available</td></tr>\n'

    content += '</table>\n'

    return content


def generate_executive(patch_data, vuln_data):
    """Generate concise executive summary."""
    now = datetime.now(timezone.utc)
    content = f"<h1>📊 Essential Eight — Executive Summary</h1>\n"
    content += f'<p class="subtitle">{now.strftime("%d %B %Y")}</p>\n'

    content += '<div class="grid">\n'

    if patch_data:
        rate = patch_data.get("compliance_rate", 0)
        content += f'<div class="card"><div class="label">Patch Compliance</div><div class="value {compliance_color(rate)}">{rate}%</div></div>\n'
        content += f'<div class="card"><div class="label">Managed Devices</div><div class="value">{patch_data.get("total_devices", 0)}</div></div>\n'
        content += f'<div class="card"><div class="label">EOL Devices</div><div class="value {"red" if patch_data.get("eol_count", 0) > 0 else "green"}">{patch_data.get("eol_count", 0)}</div></div>\n'

    if vuln_data:
        breakdown = vuln_data.get("priority_breakdown", {})
        critical = breakdown.get("P1-CRITICAL", 0)
        content += f'<div class="card"><div class="label">Critical Vulns</div><div class="value {"red" if critical > 0 else "green"}">{critical}</div></div>\n'
        content += f'<div class="card"><div class="label">CISA KEV Matches</div><div class="value {"red" if vuln_data.get("kev_matches", 0) > 0 else "green"}">{vuln_data.get("kev_matches", 0)}</div></div>\n'
        content += f'<div class="card"><div class="label">Total Findings</div><div class="value">{vuln_data.get("total_findings", 0)}</div></div>\n'

    content += '</div>\n'

    content += "<h2>Recommended Actions</h2>\n<ol>\n"

    if patch_data and patch_data.get("eol_count", 0) > 0:
        content += f'<li><strong>Upgrade {patch_data["eol_count"]} end-of-life devices</strong> — ML2 requires no unsupported OS/apps</li>\n'

    if vuln_data and vuln_data.get("kev_matches", 0) > 0:
        content += f'<li><strong>Remediate {vuln_data["kev_matches"]} CISA KEV vulnerabilities within 48 hours</strong> — actively exploited in the wild</li>\n'

    if patch_data and patch_data.get("stale_count", 0) > 0:
        content += f'<li><strong>Investigate {patch_data["stale_count"]} stale devices</strong> — not synced in 14+ days</li>\n'

    if patch_data and patch_data.get("compliance_rate", 100) < 95:
        content += '<li><strong>Improve patch compliance to 95%+</strong> — current rate below target</li>\n'

    content += "</ol>\n"

    return content


def main():
    parser = argparse.ArgumentParser(description="E8 ML2 report generator")
    parser.add_argument("--type", required=True,
                        choices=["weekly", "executive", "evidence-pack"],
                        help="Report type")
    parser.add_argument("--patch-data", help="Patch compliance JSON file")
    parser.add_argument("--vuln-data", help="Prioritised vulnerability JSON file")
    parser.add_argument("--output", default="report.html", help="Output file/directory")
    args = parser.parse_args()

    patch_data = load_json(args.patch_data)
    vuln_data = load_json(args.vuln_data)

    if not patch_data and not vuln_data:
        print("WARNING: No data files provided. Generating empty report.", file=sys.stderr)

    now = datetime.now(timezone.utc)

    if args.type == "weekly":
        title = f"E8 ML2 Weekly Readiness — {now.strftime('%d %b %Y')}"
        content = generate_weekly(patch_data, vuln_data)

    elif args.type == "executive":
        title = f"E8 ML2 Executive Summary — {now.strftime('%d %b %Y')}"
        content = generate_executive(patch_data, vuln_data)

    elif args.type == "evidence-pack":
        # Evidence pack creates a directory with individual files
        out_dir = Path(args.output)
        out_dir.mkdir(parents=True, exist_ok=True)

        # Save raw data as evidence
        if patch_data:
            with open(out_dir / "patch-compliance.json", "w") as f:
                json.dump(patch_data, f, indent=2)
        if vuln_data:
            with open(out_dir / "vulnerability-scan-prioritised.json", "w") as f:
                json.dump(vuln_data, f, indent=2)

        # Generate both reports into evidence dir
        title = f"E8 ML2 Weekly Readiness — {now.strftime('%d %b %Y')}"
        content = generate_weekly(patch_data, vuln_data)
        html = HTML_TEMPLATE.format(title=title, content=content,
                                     generated_at=now.strftime("%Y-%m-%d %H:%M UTC"))
        with open(out_dir / "weekly-report.html", "w") as f:
            f.write(html)

        title = f"E8 ML2 Executive Summary — {now.strftime('%d %b %Y')}"
        content = generate_executive(patch_data, vuln_data)
        html = HTML_TEMPLATE.format(title=title, content=content,
                                     generated_at=now.strftime("%Y-%m-%d %H:%M UTC"))
        with open(out_dir / "executive-summary.html", "w") as f:
            f.write(html)

        # Evidence manifest
        manifest = {
            "generated_at": now.isoformat(),
            "type": "Essential Eight ML2 Evidence Pack",
            "contents": [
                "patch-compliance.json — Raw patch compliance data from Intune",
                "vulnerability-scan-prioritised.json — Prioritised vulnerability scan results",
                "weekly-report.html — Weekly ML2 readiness report",
                "executive-summary.html — Executive summary",
            ]
        }
        with open(out_dir / "manifest.json", "w") as f:
            json.dump(manifest, f, indent=2)

        print(f"Evidence pack written to {out_dir}/")
        return

    html = HTML_TEMPLATE.format(title=title, content=content,
                                 generated_at=now.strftime("%Y-%m-%d %H:%M UTC"))

    with open(args.output, "w") as f:
        f.write(html)
    print(f"Report written to {args.output}")


if __name__ == "__main__":
    main()
